// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TEST_API.Models;

namespace TEST_API.Models
{
    public partial class TEST_MAINDbContext
    {
        private ITEST_MAINDbContextProcedures _procedures;

        public virtual ITEST_MAINDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TEST_MAINDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITEST_MAINDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TEST_MAINDbContextProcedures : ITEST_MAINDbContextProcedures
    {
        private readonly TEST_MAINDbContext _context;

        public TEST_MAINDbContextProcedures(TEST_MAINDbContext context)
        {
            _context = context;
        }
    }
}
