version: "3.9"

services:
  sqlserver2022:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: "sqlserver2022"
    restart: always
    ports: 
        - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=1e08ce1d-c13b-4f4a-b5fe-15c466831edc
