// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEST_API_CodeFirst.Models;

#nullable disable

namespace TEST_API_CodeFirst.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250417100217_AddNavigators")]
    partial class AddNavigators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEST_API_CodeFirst.Models.Gender", b =>
                {
                    b.Property<int>("Gender_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gender_ID"));

                    b.Property<string>("GenderText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gender_ID");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("TEST_API_CodeFirst.Models.Race", b =>
                {
                    b.Property<int>("Race_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Race_ID"));

                    b.Property<string>("RaceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Race_ID");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("TEST_API_CodeFirst.Models.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Role_ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TEST_API_CodeFirst.Models.Title", b =>
                {
                    b.Property<int>("Title_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Title_ID"));

                    b.Property<string>("TitleText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title_ID");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("TEST_API_CodeFirst.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender_ID")
                        .HasColumnType("int");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Race_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Role_ID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Title_ID")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("Gender_ID");

                    b.HasIndex("Race_ID");

                    b.HasIndex("Role_ID");

                    b.HasIndex("Title_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TEST_API_CodeFirst.Models.User", b =>
                {
                    b.HasOne("TEST_API_CodeFirst.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("Gender_ID");

                    b.HasOne("TEST_API_CodeFirst.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("Race_ID");

                    b.HasOne("TEST_API_CodeFirst.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_ID");

                    b.HasOne("TEST_API_CodeFirst.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("Title_ID");

                    b.Navigation("Gender");

                    b.Navigation("Race");

                    b.Navigation("Role");

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
